image: /home/manu/egguard/egguard_nav2_system/config/my_map.pgm # cambiar "juan" por el nombre de usuario
mode: trinary
resolution: 0.05
origin: [-6.08, -10.3, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25